# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Application Benchmarks Tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    # run every day at 1AM
    - cron: '0 1 * * *'

jobs:
  Checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-libraries
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-main-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-applications
      - name: Install Dependencies
        run: |
          sudo apt-get -y install pandoc graphviz
          sudo apt-get -y install python3-enchant
          sudo apt-get -y install hunspell-en-us
          pip install pyenchant
        shell: bash
      - run:  pip check
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make copyright
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make spell
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make style
        if: ${{ !cancelled() }}
        shell: bash
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-libraries
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-main-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-applications
      - run: make lint
        if: ${{ !cancelled() }}
        shell: bash
      - run: make mypy
        if: ${{ !cancelled() }}
        shell: bash
  Benchmarks-Dev:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-libraries
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-main-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-applications
      - name:  Finance Benchmarks
        run: |
          make machine TARGET=finance ASVOPTS=--yes
          make benchmark_dev TARGET=finance || true
        shell: bash
      - name: Machine Learning Benchmarks
        run: |
          make machine TARGET=machine_learning ASVOPTS=--yes
          make benchmark_dev TARGET=machine_learning || true
        if: ${{ !cancelled() }}
        shell: bash
      - name: Nature
        run: |
          make machine TARGET=nature ASVOPTS=--yes
          make benchmark_dev TARGET=nature || true
        if: ${{ !cancelled() }}
        shell: bash
      - name: Optimization
        run: |
          make machine TARGET=optimization ASVOPTS=--yes
          make benchmark_dev TARGET=optimization
        if: ${{ !cancelled() }}
        shell: bash